import { createHash } from "node:crypto";
import {
  mkdir,
  readdir,
  unlink,
  writeFile,
} from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { DEFAULT_PHRASE_SETTINGS } from "../data/default-phrase-settings.js";
import { WJAZZD_CHORDS } from "../data/wjazzd-chords.js";
import {
  DEFAULT_PERFORMERS,
  WJAZZD_PERFORMERS,
  WJAZZD_SOLOS,
} from "../data/wjazzd-solos.js";
import {
  phraseEventsWithEdits,
  resolvePhraseSettings,
} from "../src/phrase-settings.js";

const INDEX_SCHEMA_VERSION = 1;
const BLOCK_SIZE = 8;
const DEFAULT_OUTPUT_URL = new URL("../data/wjazzd-index.js", import.meta.url);
const STRUCTURAL_EXCLUSIONS = Object.freeze([
  null,
  "very-short-v1",
  "rapid-run-v1",
  "dense-burst-v1",
]);

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function adjustedEvents(events, storedSettings) {
  const sourceEvents = phraseEventsWithEdits(events, storedSettings);
  const settings = resolvePhraseSettings(storedSettings, sourceEvents.length);
  const truncated = sourceEvents.slice(0, settings.notesMax);
  const ignored = new Set(
    truncated
      .map((event, index) => ({
        index,
        duration: Number(event?.[2]) || 0,
      }))
      .sort(
        (left, right) =>
          left.duration - right.duration || left.index - right.index,
      )
      .slice(0, settings.ignoredShortestNotes)
      .map(({ index }) => index),
  );
  return ignored.size
    ? truncated.filter((_, index) => !ignored.has(index))
    : truncated;
}

function transpositionMinimum(events) {
  const notes = events.map(([midi]) => Number(midi)).filter(Number.isFinite);
  if (!notes.length) return -5;
  const phraseCenter = (Math.min(...notes) + Math.max(...notes)) / 2;
  const minimum = Math.max(
    -11,
    Math.min(0, Math.round(66 - phraseCenter - 5.5)),
  );
  return Object.is(minimum, -0) ? "-0" : minimum;
}

function maximumRapidRun(events, maximumInterOnsetSeconds) {
  let maximum = events.length ? 1 : 0;
  let current = maximum;
  for (let index = 1; index < events.length; index += 1) {
    const interOnsetSeconds = events[index][1] - events[index - 1][1];
    if (interOnsetSeconds <= maximumInterOnsetSeconds + Number.EPSILON) {
      current += 1;
      maximum = Math.max(maximum, current);
    } else {
      current = 1;
    }
  }
  return maximum;
}

function maximumNotesInWindow(events, maximumWindowSeconds) {
  let maximum = 0;
  let start = 0;
  for (let end = 0; end < events.length; end += 1) {
    while (
      start < end &&
      events[end][1] - events[start][1] >
        maximumWindowSeconds + Number.EPSILON
    ) {
      start += 1;
    }
    maximum = Math.max(maximum, end - start + 1);
  }
  return maximum;
}

function structuralExclusion(events) {
  if (events.length <= 4) return [1, null];
  const rapidRunNotes = maximumRapidRun(events, 0.18);
  if (rapidRunNotes >= 14) return [2, rapidRunNotes];
  const rapidWindowNotes = maximumNotesInWindow(events, 0.5);
  return rapidWindowNotes >= 7 ? [3, rapidWindowNotes] : [0, null];
}

function phraseTuple(solo, phrase) {
  const [start, end, phraseNumber] = phrase;
  const events = solo.events.slice(start, end + 1);
  const phraseKey = `${solo.id}:${phraseNumber}`;
  const adjusted = adjustedEvents(
    events,
    DEFAULT_PHRASE_SETTINGS[phraseKey],
  );
  const [exclusionCode, exclusionMetric] = structuralExclusion(events);
  return [
    String(phraseNumber),
    events.length,
    adjusted.length,
    transpositionMinimum(adjusted),
    exclusionCode,
    exclusionMetric,
  ];
}

function outputUrlFromArgument() {
  const argument = process.argv[2];
  return argument
    ? pathToFileURL(resolve(argument))
    : DEFAULT_OUTPUT_URL;
}

async function cleanGeneratedBlocks(blocksDirectoryUrl) {
  let names = [];
  try {
    names = await readdir(blocksDirectoryUrl);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  await Promise.all(
    names
      .filter((name) => /^block-\d{3}\.json$/.test(name))
      .map((name) => unlink(new URL(name, blocksDirectoryUrl))),
  );
}

function indexSource({
  corpusVersion,
  indexVersion,
  blocks,
  soloIndex,
  phraseCount,
  fingerprints,
}) {
  return [
    "// Generated by scripts/generate_wjazzd_chunks.mjs. Do not edit by hand.",
    `export const WJAZZD_INDEX_SCHEMA_VERSION = ${INDEX_SCHEMA_VERSION};`,
    `export const WJAZZD_CORPUS_VERSION = ${JSON.stringify(corpusVersion)};`,
    `export const WJAZZD_INDEX_VERSION = ${JSON.stringify(indexVersion)};`,
    `export const WJAZZD_BLOCK_SIZE = ${BLOCK_SIZE};`,
    "export const WJAZZD_PHRASE_INDEX_FIELDS = Object.freeze({" +
      "phrase:0,fullPhraseNoteCount:1,noteCount:2," +
      "transpositionMinimum:3,structuralExclusion:4," +
      "structuralMetric:5});",
    `export const WJAZZD_STRUCTURAL_EXCLUSIONS = Object.freeze(${JSON.stringify(
      STRUCTURAL_EXCLUSIONS,
    )});`,
    `export const WJAZZD_CORPUS_STATS = Object.freeze(${JSON.stringify({
      soloCount: WJAZZD_SOLOS.length,
      performerCount: WJAZZD_PERFORMERS.length,
      phraseCount,
      eventCount: WJAZZD_SOLOS.reduce(
        (total, solo) => total + solo.events.length,
        0,
      ),
      beatCount: WJAZZD_SOLOS.reduce(
        (total, solo) => total + solo.beats.length,
        0,
      ),
      chordCount: Object.values(WJAZZD_CHORDS).reduce(
        (total, chords) => total + chords.length,
        0,
      ),
    })});`,
    `export const WJAZZD_CORPUS_FINGERPRINTS = Object.freeze(${JSON.stringify(
      fingerprints,
    )});`,
    `export const WJAZZD_BLOCKS = Object.freeze(${JSON.stringify(blocks)});`,
    `export const WJAZZD_SOLO_INDEX = Object.freeze(${JSON.stringify(
      soloIndex,
    )});`,
    `export const WJAZZD_PERFORMERS = Object.freeze(${JSON.stringify(
      WJAZZD_PERFORMERS,
    )});`,
    `export const DEFAULT_PERFORMERS = Object.freeze(${JSON.stringify(
      DEFAULT_PERFORMERS,
    )});`,
    "",
  ].join("\n");
}

async function main() {
  const outputUrl = outputUrlFromArgument();
  const blocksDirectoryUrl = new URL("./wjazzd-blocks/", outputUrl);
  await mkdir(blocksDirectoryUrl, { recursive: true });
  await cleanGeneratedBlocks(blocksDirectoryUrl);

  const corpusPayload = JSON.stringify({
    solos: WJAZZD_SOLOS,
    performers: WJAZZD_PERFORMERS,
    defaultPerformers: DEFAULT_PERFORMERS,
    chords: WJAZZD_CHORDS,
  });
  const corpusVersion = sha256(corpusPayload);
  const indexVersion = sha256(
    JSON.stringify({
      corpusVersion,
      defaultPhraseSettings: DEFAULT_PHRASE_SETTINGS,
    }),
  );
  const blocks = [];
  const soloIndex = [];

  for (
    let start = 0, blockNumber = 0;
    start < WJAZZD_SOLOS.length;
    start += BLOCK_SIZE, blockNumber += 1
  ) {
    const id = String(blockNumber).padStart(3, "0");
    const fileName = `block-${id}.json`;
    const solos = WJAZZD_SOLOS.slice(start, start + BLOCK_SIZE);
    const block = {
      schemaVersion: INDEX_SCHEMA_VERSION,
      corpusVersion,
      blockId: id,
      solos,
      chords: Object.fromEntries(
        solos.map((solo) => [solo.id, WJAZZD_CHORDS[solo.id] ?? []]),
      ),
    };
    await writeFile(
      new URL(fileName, blocksDirectoryUrl),
      `${JSON.stringify(block)}\n`,
      "utf8",
    );
    blocks.push({
      id,
      url: `./wjazzd-blocks/${fileName}`,
      soloCount: solos.length,
    });
    for (const solo of solos) {
      soloIndex.push({
        id: solo.id,
        performer: solo.performer,
        title: solo.title,
        sourceUrl: solo.sourceUrl,
        block: blockNumber,
        phrases: solo.phrases.map((phrase) => phraseTuple(solo, phrase)),
      });
    }
  }

  const soloIds = WJAZZD_SOLOS.map(({ id }) => id);
  const phraseKeys = WJAZZD_SOLOS.flatMap((solo) =>
    solo.phrases.map((phrase) => `${solo.id}:${phrase[2]}`),
  );
  const fingerprints = {
    soloIdsSha256: sha256(soloIds.join("\n")),
    phraseKeysSha256: sha256(phraseKeys.join("\n")),
  };
  await writeFile(
    new URL("manifest.json", blocksDirectoryUrl),
    `${JSON.stringify({
      schemaVersion: INDEX_SCHEMA_VERSION,
      corpusVersion,
      blocks: blocks.map(({ id, url, soloCount }) => ({
        id,
        url: url.replace("./wjazzd-blocks/", "./"),
        soloCount,
      })),
    })}\n`,
    "utf8",
  );
  await writeFile(
    outputUrl,
    indexSource({
      corpusVersion,
      indexVersion,
      blocks,
      soloIndex,
      phraseCount: phraseKeys.length,
      fingerprints,
    }),
    "utf8",
  );
  console.log(
    `${WJAZZD_SOLOS.length} solos et ${phraseKeys.length} phrases ` +
      `répartis dans ${blocks.length} blocs (${fileURLToPath(outputUrl)})`,
  );
}

await main();
