import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (quoted) {
      if (character === '"' && text[index + 1] === '"') {
        cell += '"';
        index += 1;
      } else if (character === '"') {
        quoted = false;
      } else {
        cell += character;
      }
    } else if (character === '"') {
      quoted = true;
    } else if (character === ";") {
      row.push(cell);
      cell = "";
    } else if (character === "\n") {
      row.push(cell.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += character;
    }
  }

  if (cell || row.length) {
    row.push(cell.replace(/\r$/, ""));
    rows.push(row);
  }
  return rows.filter((cells) => cells.some(Boolean));
}

function objectFromRow(headers, cells) {
  return Object.fromEntries(
    headers.map((header, index) => [header, cells[index] ?? ""]),
  );
}

const [inputPath, outputPath = "data/default-ratings.js"] = process.argv.slice(2);
if (!inputPath) {
  throw new Error(
    "Usage: node scripts/generate_ratings_data.mjs <export.csv> [data/default-ratings.js]",
  );
}

const text = (await readFile(inputPath, "utf8")).replace(/^\uFEFF/, "");
const [headers, ...rows] = parseCsv(text);
const phraseRatings = {};
const ratingScopes = [];

for (const cells of rows) {
  const entry = objectFromRow(headers, cells);
  const scope = entry.portee || "phrase";
  const rating = Number(entry.etoiles);
  if (![1, 2, 3].includes(rating)) continue;

  if (scope === "phrase") {
    const phraseKey = entry.identifiant || entry.phrase_id;
    if (!phraseKey) continue;
    phraseRatings[phraseKey] = {
      rating,
      updatedAt: entry.mise_a_jour || null,
      soloId: phraseKey.split(":").slice(0, -1).join(":"),
      performer: entry.musicien || null,
      title: entry.morceau || null,
      phrase: entry.phrase || phraseKey.split(":").at(-1),
      sourceUrl: entry.source_url || null,
      origin: "embedded",
    };
    continue;
  }

  const scopeId = entry.identifiant;
  if (!scopeId || !["tune", "performer"].includes(scope)) continue;
  ratingScopes.push({
    scope,
    scopeId,
    rating,
    performer: entry.musicien || null,
    title: entry.morceau || null,
    origin: "embedded",
    sampleSize: Number(entry.taille_echantillon) || null,
    agreement: Number(entry.accord) || null,
    coverage: Number(entry.couverture) || null,
    updatedAt: entry.mise_a_jour || null,
  });
}

const source = `// Generated by scripts/generate_ratings_data.mjs.
// Rebuild this file from the latest protocol export instead of editing it by hand.
export const DEFAULT_PHRASE_RATINGS = Object.freeze(${JSON.stringify(
  Object.fromEntries(Object.entries(phraseRatings).sort()),
  null,
  2,
)});

export const DEFAULT_RATING_SCOPES = Object.freeze(${JSON.stringify(
  ratingScopes.sort((left, right) =>
    `${left.scope}:${left.scopeId}`.localeCompare(
      `${right.scope}:${right.scopeId}`,
    ),
  ),
  null,
  2,
)});
`;

await writeFile(outputPath, source);
console.log(
  `Generated ${Object.keys(phraseRatings).length} phrase ratings and ${ratingScopes.length} scope ratings in ${outputPath}.`,
);
