import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import process from "node:process";

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (quoted) {
      if (character === '"' && text[index + 1] === '"') {
        cell += '"';
        index += 1;
      } else if (character === '"') {
        quoted = false;
      } else {
        cell += character;
      }
    } else if (character === '"') {
      quoted = true;
    } else if (character === ";") {
      row.push(cell);
      cell = "";
    } else if (character === "\n") {
      row.push(cell.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += character;
    }
  }

  if (cell || row.length) {
    row.push(cell.replace(/\r$/, ""));
    rows.push(row);
  }
  return rows.filter((cells) => cells.some(Boolean));
}

function objectFromRow(headers, cells) {
  return Object.fromEntries(
    headers.map((header, index) => [header, cells[index] ?? ""]),
  );
}

function parseEditedEvents(value) {
  if (!value) return null;
  try {
    const events = JSON.parse(value);
    if (!Array.isArray(events) || events.length < 1) return null;
    const normalized = events.map((event) => {
      if (!Array.isArray(event)) return null;
      const midi = Math.round(Number(event[0]));
      const onset = Number(event[1]);
      const duration = Number(event[2]);
      const bar = event[3] === null || event[3] === undefined
        ? null
        : Number(event[3]);
      if (
        !Number.isFinite(midi) ||
        midi < 0 ||
        midi > 127 ||
        !Number.isFinite(onset) ||
        onset < 0 ||
        !Number.isFinite(duration) ||
        duration <= 0
      ) {
        return null;
      }
      return [
        midi,
        Number(onset.toFixed(4)),
        Number(duration.toFixed(4)),
        Number.isFinite(bar) ? Math.round(bar) : null,
      ];
    });
    return normalized.some((event) => !event) ? null : normalized;
  } catch {
    return null;
  }
}

const [
  inputPath,
  outputPath = "data/default-ratings.js",
  phraseSettingsOutputPath = join(
    dirname(outputPath),
    "default-phrase-settings.js",
  ),
] = process.argv.slice(2);
if (!inputPath) {
  throw new Error(
    "Usage: node scripts/generate_ratings_data.mjs <export.csv> [data/default-ratings.js] [data/default-phrase-settings.js]",
  );
}

const text = (await readFile(inputPath, "utf8")).replace(/^\uFEFF/, "");
const [headers, ...rows] = parseCsv(text);
const phraseRatings = {};
const phraseSettings = {};
const ratingScopes = [];

for (const cells of rows) {
  const entry = objectFromRow(headers, cells);
  const scope = entry.portee || "phrase";
  const rating = Number(entry.etoiles);

  if (scope === "phrase") {
    const phraseKey = entry.identifiant || entry.phrase_id;
    if (!phraseKey) continue;
    const notesMax = Number(entry.notes_max);
    const ignoredShortestNotes = Number(entry.notes_courtes_ignorees);
    const editedEvents = parseEditedEvents(
      entry.evenements_midi_corriges,
    );
    const hasNotesMax =
      entry.notes_max !== "" &&
      Number.isFinite(notesMax) &&
      notesMax >= 1;
    const hasIgnoredShortestNotes =
      entry.notes_courtes_ignorees !== "" &&
      Number.isFinite(ignoredShortestNotes) &&
      ignoredShortestNotes >= 0;
    if (hasNotesMax || hasIgnoredShortestNotes || editedEvents) {
      phraseSettings[phraseKey] = {
        notesMax: hasNotesMax ? Math.round(notesMax) : 20,
        ignoredShortestNotes: hasIgnoredShortestNotes
          ? Math.round(ignoredShortestNotes)
          : 0,
        ...(editedEvents ? { editedEvents } : {}),
        updatedAt:
          entry.reglages_mise_a_jour || entry.mise_a_jour || null,
      };
    }
    if ([1, 2, 3].includes(rating)) {
      phraseRatings[phraseKey] = {
        rating,
        updatedAt: entry.mise_a_jour || null,
        soloId: phraseKey.split(":").slice(0, -1).join(":"),
        performer: entry.musicien || null,
        title: entry.morceau || null,
        phrase: entry.phrase || phraseKey.split(":").at(-1),
        sourceUrl: entry.source_url || null,
        origin: "embedded",
      };
    }
    continue;
  }

  if (![1, 2, 3].includes(rating)) continue;
  const scopeId = entry.identifiant;
  if (
    !scopeId ||
    !["tune", "performer"].includes(scope) ||
    rating !== 1
  ) {
    continue;
  }
  ratingScopes.push({
    scope,
    scopeId,
    rating,
    performer: entry.musicien || null,
    title: entry.morceau || null,
    origin: entry.origine || "embedded",
    sampleSize: Number(entry.taille_echantillon) || null,
    agreement: Number(entry.accord) || null,
    coverage: Number(entry.couverture) || null,
    updatedAt: entry.mise_a_jour || null,
  });
}

const ratingsSource = `// Generated by scripts/generate_ratings_data.mjs.
// Rebuild this file from the latest protocol export instead of editing it by hand.
export const DEFAULT_PHRASE_RATINGS = Object.freeze(${JSON.stringify(
  Object.fromEntries(Object.entries(phraseRatings).sort()),
  null,
  2,
)});

export const DEFAULT_RATING_SCOPES = Object.freeze(${JSON.stringify(
  ratingScopes.sort((left, right) =>
    `${left.scope}:${left.scopeId}`.localeCompare(
      `${right.scope}:${right.scopeId}`,
    ),
  ),
  null,
  2,
)});
`;

const phraseSettingsSource = `// Generated by scripts/generate_ratings_data.mjs.
// Rebuild this file from the latest data export instead of editing it by hand.
export const DEFAULT_PHRASE_SETTINGS = Object.freeze(${JSON.stringify(
  Object.fromEntries(Object.entries(phraseSettings).sort()),
  null,
  2,
)});
`;

await Promise.all([
  writeFile(outputPath, ratingsSource),
  writeFile(phraseSettingsOutputPath, phraseSettingsSource),
]);
console.log(
  `Generated ${Object.keys(phraseRatings).length} phrase ratings and ${ratingScopes.length} scope ratings in ${outputPath}; ${Object.keys(phraseSettings).length} phrase settings in ${phraseSettingsOutputPath}.`,
);
